# Generated by Django 2.0.1 on 2020-02-27 07:44

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('t_contract_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateField(blank=True, null=True)),
                ('stop_time', models.DateField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contract',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TBrowsingHistory',
            fields=[
                ('browsing_history_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 't_browsing_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TChatmsg',
            fields=[
                ('chatmsg_id', models.AutoField(primary_key=True, serialize=False)),
                ('chatmsg_time', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_chatmsg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TComment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_time', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('state', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'db_table': 't_comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TComplaint',
            fields=[
                ('fadeback_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('state', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'db_table': 't_complaint',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TFavorite',
            fields=[
                ('favorite_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 't_favorite',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TFeedback',
            fields=[
                ('fadeback_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_feedback',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='THouse',
            fields=[
                ('house_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('publish_time', models.DateField(blank=True, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('sale_status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_house',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='THouseVerify',
            fields=[
                ('verify_id', models.AutoField(primary_key=True, serialize=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('verify_status', models.IntegerField(choices=[(0, '审核中'), (1, '已通过'), (2, '未通过')], default=0)),
            ],
            options={
                'db_table': 't_house_verify',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TLuckyTicket',
            fields=[
                ('lucky_ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('money', models.IntegerField(blank=True, null=True)),
                ('begin_time', models.DateField(blank=True, null=True)),
                ('end_time', models.DateField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 't_lucky_ticket',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TMessage',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 't_message',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TOrder',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_number', models.CharField(blank=True, max_length=16, null=True)),
                ('enter_time', models.TimeField(blank=True, null=True)),
                ('exit_time', models.TimeField(blank=True, null=True)),
                ('hire_price', models.FloatField(blank=True, null=True)),
                ('cash_price', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('order_status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TPanda',
            fields=[
                ('panda_id', models.AutoField(primary_key=True, serialize=False)),
                ('detail_content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_panda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TScore',
            fields=[
                ('score_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_score',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TService',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, null=True)),
                ('service_status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_service',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TSlidesshow',
            fields=[
                ('slidesshow_id', models.AutoField(primary_key=True, serialize=False)),
                ('ord', models.IntegerField()),
            ],
            options={
                'db_table': 't_slidesshow',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TSysMenu',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_name', models.CharField(blank=True, max_length=20, null=True)),
                ('ord', models.IntegerField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 't_sys_menu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TSysRole',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=20)),
                ('role_code', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 't_sys_role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TSysRoleMenu',
            fields=[
                ('role_id', models.IntegerField(blank=True, null=True)),
                ('sys_menu_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 't_sys_role_menu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TSysUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('role_id', models.IntegerField(blank=True, null=True)),
                ('password', models.CharField(blank=True, max_length=32, null=True)),
                ('nick_name', models.CharField(blank=True, max_length=20, null=True)),
                ('head', models.ImageField(blank=True, null=True, upload_to='')),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 't_sys_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TTradingrecord',
            fields=[
                ('tradingrecord_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('payment_type', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_tradingrecord',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TULuckyTicket',
            fields=[
                ('u_lucky_ticketid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 't_u_lucky_ticket',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('sex', models.CharField(blank=True, max_length=20, null=True)),
                ('identity_number', models.CharField(blank=True, max_length=18, null=True)),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('img', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.CharField(blank=True, max_length=60, null=True)),
                ('password', models.CharField(blank=True, max_length=30, null=True)),
                ('has_real_name', models.IntegerField(blank=True, null=True)),
                ('is_member', models.IntegerField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('dimension', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TPublicNotice',
            fields=[
                ('public_time', models.DateTimeField(auto_created=True, blank=True)),
                ('public_notice_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', tinymce.models.HTMLField(null=True)),
                ('public_title', models.CharField(max_length=50, null=True)),
                ('public_remarks', models.TextField(blank=True, null=True)),
                ('public_status', models.IntegerField(choices=[(0, '待审核'), (1, '已通过'), (2, '未通过')], default=0)),
            ],
            options={
                'db_table': 't_public_notice',
                'ordering': ['-public_time'],
            },
        ),
    ]
