# Generated by Django 2.0.1 on 2020-02-23 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tpublicnotice',
            options={},
        ),
    ]
