# Generated by Django 2.0.1 on 2020-02-23 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200223_1552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tpublicnotice',
            options={'managed': False},
        ),
    ]
