# Generated by Django 2.0.1 on 2020-02-23 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20200223_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tpublicnotice',
            options={},
        ),
    ]
